### ISSUE TITLE
docker persistence configuration

### ISSUE THREAD

**Issue by jorgesanmartin** [wso2/streaming-integrator#122]
Trying to configure deployment.yaml with persistance enabled and using the following configuration (following the documentation)

state.persistence:
  enabled: true
  intervalInMin: 1
  revisionsToKeep: 2
  persistenceStore: org.wso2.carbon.stream.processor.core.persistence.FileSystemPersistenceStore
  config:
    location: siddhi-app-persistence

I get the following error when container starts:

java.lang.ClassNotFoundException: org.wso2.carbon.stream.processor.core.persistence.FileSystemPersistenceStore cannot be found by org.wso2.carbon.streaming.integrator.core_3.0.13

I'm using the base image wso2/streaming-integrator:1.0.0
Do I need to include any additional library in the image in order to activate persistance?

**Comment by senthuran16** [comment]
Hi @jorgesanmartin ,
Can you please try replacing `persistenceStore` in your deployment.yaml with the following: 
```
persistenceStore: org.wso2.carbon.streaming.integrator.core.persistence.FileSystemPersistenceStore
```

**Comment by jorgesanmartin** [comment]
Got it!!! Working...indeed I checked org.wso2.carbon.streaming.integrator.core_3.0.13.jar and i found the class inside.. Thank you very much.
Maybe documentation should be updated since it reuses the streaming processor configuration.
