### ISSUE TITLE
Allow escapes for siddhi execution JSON extension toString method

### ISSUE THREAD

**Issue by lkokila** [wso2/streaming-integrator#129]
**Description:**
Currently toString method does not put escapes when needed. Thus need to provide capability to include the escaping functionality for JSON extension.
**Affected Product Version:** Streaming Integrator 1.0.0

**Comment by dilini-muthumala** [comment]
Fixed in https://github.com/dilini-muthumala/siddhi-execution-json/commit/0369349719dde825ae3332a8849ecd57907a9ab0
