### ISSUE TITLE
Siddhi IO CDC throws Producer failure java.lang.IllegalArgumentException: Invalid identifier: error with PostgreSQL

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/streaming-integrator#147]
**Description:**
Hi,

When we try to run CDC with PostgreSQL, Producer failure java.lang.IllegalArgumentException: Invalid identifier: error throws from Debezium client connector.

To mitigate this issue debezium version should bump to 1.1.0 or newer version.

**Affected Product Version:**
SI 1.1.0

**Comment by dilini-muthumala** [comment]
Fixed in:
https://github.com/siddhi-io/siddhi-io-cdc/pull/63
https://github.com/siddhi-io/siddhi-io-cdc/pull/65

**Comment by kiwinesian** [comment]
Hi there @dilini-muthumala 

Is it possible that this issue still persist on the `streaming-integrator-tooling` version 1.1.0?
I've been trying to test it using the tooling and I'm seeing the exact same issue.

Installed in Debian via `apt`
