### ISSUE TITLE
Is there any special configuration that failed to install the Streaming Integrator using Kubernetes

### ISSUE THREAD

**Issue by liwh1111** [wso2/streaming-integrator#160]
Is there any special configuration that failed to install the Streaming Integrator using Kubernetes? I installed it according to the official documents

![image](https://user-images.githubusercontent.com/63097736/102299286-abc9cd80-3f8d-11eb-8fd5-647a1676b18b.png)

![image](https://user-images.githubusercontent.com/63097736/102299247-981e6700-3f8d-11eb-86e8-85c0bf74610f.png)

**Comment by senthuran16** [comment]
Hi @liwh1111,
Can you please provide us with more context on what issue are you facing?

**Comment by liwh1111** [comment]
Resolved, the YAML file serviceAccount you provided does not correspond

![image](https://user-images.githubusercontent.com/63097736/102316688-556e8600-3fb1-11eb-9819-0ddda109075b.png)
