### ISSUE TITLE
Allow slot replication selection for PostgreSQL database

### ISSUE THREAD

**Issue by kiwinesian** [wso2/streaming-integrator#166]
**Description:**
PostgreSQL requires a unique replication slot for each method: CREATE, UPDATE, DELETE
The siddhi-io-cdc doesn't have the option to change slot.name and create respective replication slot for each method.

slot.name is default to Debezium at the moment.

**Suggested Labels:**
psql, postgresql, replication

**Suggested Assignees:**

**Affected Product Version:**
1.1.0

**OS, DB, other environment details and versions:**    
Debian

**Steps to reproduce:**
Regular `psql` connection

**Related Issues:**

**Comment by kiwinesian** [comment]
no help? :(

**Comment by AnuGayan** [comment]
This can be achieved with pool.properties and connector.properties which can be provided as parameters when defining the CDC source
