### ISSUE TITLE
runtime and tooling are not behaving the same way

### ISSUE THREAD

**Issue by kiwinesian** [wso2/streaming-integrator#177]
**Description:**
Running in production returns the following error when using `http-call` and/ `http-call-response`

```
[2021-01-20 01:03:57,850] ERROR {org.wso2.transport.http.netty.contractimpl.listener.HttpExceptionHandler} - Exception occurred in HTTP inbound channel pipeline : {} java.io.IOException: Connection reset by peer
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ramindu90** [comment]
@kiwinesian could you please share the siddhi app used? and other related environment details?

**Comment by AnuGayan** [comment]
Will be closing since didn't observe this issue, please feel free to open if have more information about this
