### ISSUE TITLE
[Async API] Generate view description box cursor is centered

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/streaming-integrator#202]
**Description:**
Please refer the image
<img width="1122" alt="Screen Shot 2021-03-10 at 6 36 05 PM" src="https://user-images.githubusercontent.com/7592890/110634053-8553b100-81cf-11eb-8680-d382b652161c.png">

**Affected Product Version:**
wso2si-tooling-4.0.0-SNAPSHOT - latest build - from 
https://wso2.org/jenkins/view/products/job/products/job/streaming-integrator-tooling/637/

**OS, DB, other environment details and versions:**  
Mac OS  10.13.1 
Google Chrome Version 88.0.4324.146 (Official Build) (x86_64)

**Comment by ramindu90** [comment]
Fixed with PR https://github.com/wso2/carbon-analytics/pull/1920
