### ISSUE TITLE
Can't view Async API View from Design mode

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/streaming-integrator#203]
**Steps to reproduce:**
1. From  source view, go to design view
2. From the Design View, Click on 'Async API View' button 
3. It does not take you to Asyn API view instead stays on the design view
<img width="1101" alt="Screen Shot 2021-03-10 at 10 02 48 PM" src="https://user-images.githubusercontent.com/7592890/110663348-56980380-81ec-11eb-9829-f937d579a96f.png">

4. Now click Code View. It takes you to Source view.
5. From Source view, click 'Async API View' button 
6. It takes you to the design view

Also intermittently, 'Source View' button was displayed on the Source View itself. See screenshot below:
<img width="1290" alt="Screen Shot 2021-03-10 at 10 08 11 PM" src="https://user-images.githubusercontent.com/7592890/110664393-5d734600-81ed-11eb-9e25-2a1b3d2b861f.png">

**Affected Product Version:**
wso2si-tooling-4.0.0-SNAPSHOT downloaded from:
https://wso2.org/jenkins/view/products/job/products/job/streaming-integrator-tooling/637/

**OS, DB, other environment details and versions:**    
Mac OS 10.13.1
Google Chrome Version 88.0.4324.146 (Official Build) (x86_64)

**Comment by ramindu90** [comment]
Fixed with https://github.com/wso2/carbon-analytics/pull/1922
