### ISSUE TITLE
[UI] [Asnyc API view] The arrow button in the bottom right of the screen is difficult to be used

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/streaming-integrator#204]
**Description:**
Please see the screenshot below.
The > arrow button in the bottom right of the screen is difficult to be used because of the buttons on top of it.
<img width="1117" alt="Screen Shot 2021-03-12 at 8 33 01 PM" src="https://user-images.githubusercontent.com/7592890/110958373-a56fa580-8372-11eb-8859-f65582fb733c.png">

**Affected Product Version:**
wso2si-tooling-4.0.0-SNAPSHOT - build from
https://wso2.org/jenkins/view/products/job/products/job/streaming-integrator-tooling/637/

**Comment by dnwick** [comment]
This is fixed now
