### ISSUE TITLE
jni-provider.bat and spi-provider.bat scripts are not working

### ISSUE THREAD

**Issue by ug205** [wso2/streaming-integrator#208]
**Description:**
jni-provider.bat and spi-provider.bat scripts are not working as expected.

**Affected Product Version:**
sp.4.X.X
si-1.X.X

**Steps to reproduce:**
Run jni-provider.bat and spi-provider.bat scripts in an windows enviroment using the steps given in [1]  under the sub topic "Configure Streaming Integrator".

[1].https://medium.com/@lasanthas/configuring-oracle-cdc-with-wso2-streaming-integrator-ba74eae260f5

**Comment by AnuGayan** [comment]
This is fixed in the latest released beta pack
