### ISSUE TITLE
Streaming Integrator tooling Export for Docker uses old base image

### ISSUE THREAD

**Issue by arunans23** [wso2/streaming-integrator#250]
**Description:**

When you use [Export for Docker](https://apim.docs.wso2.com/en/latest/develop/streaming-apps/exporting-siddhi-applications/#exporting-siddhi-applications-as-a-docker-image) feature in Streaming Integrator tooling to export Docker image, it uses SI 1.0.0 (old) as the base image. Ideally, it should use the Tooling's version or it should have the control to select the base image.

**Affected Product Version:**
SI tooling 4.0.0

**Comment by dnwick** [comment]
Fixed in https://github.com/wso2/carbon-analytics/pull/1964
