### ISSUE TITLE
[Document Issue] Need a separate section for Active-Active deployment scenario

### ISSUE THREAD

**Issue by AnuGayan** [wso2/streaming-integrator#64]
**Description:**
Configurations that needed to be done in Active-Active deployment are not there in the current SI documentations. Shall we add a separate section for Active-Active deployment ?

(1) https://docs.wso2.com/display/EI640/Active-Active+Deployment

**Affected Product Version:**
wso2si 1.0.0

**Related Issues:**

**Comment by AnuGayan** [comment]
@RukshiW

**Comment by RukshiW** [comment]
This was added via [1].

[1] https://github.com/wso2/docs-ei/pull/1137
