### ISSUE TITLE
[SP] Add support to LDAP based JDBC URL

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/streaming-integrator#65]
**Description:**
Currently we don't support LDAP based database model with our products such as below to define the databases in deployment.yaml file,

> jdbc:oracle:thin:@ldap://oid.hostname.net:3060/cn=OracleContext,dc=test,dc=net/mydb

and we need to implement this as an improvement to exsiting products.

**Suggested Labels:**
Stream Processor, 4.2.0, 4.3.0, 4.4.0

**Affected Product Version:**
Stream Processor 4.2.0

**Comment by dnwick** [comment]
Reducing priority since this is a old product and will prioritize if the need arises
