### ISSUE TITLE
[Windows] NPE in ICF Provider tool

### ISSUE THREAD

**Issue by lasanthaS** [wso2/streaming-integrator#67]
**Description:**
Refer the carbon-kernel issue for details at https://github.com/wso2/carbon-kernel/issues/2601.

**Affected Product Version:**
1.0.0

**Related Issues:**
https://github.com/wso2/carbon-kernel/issues/2601

**Comment by ramindu90** [comment]
Fixed with https://github.com/wso2/carbon-kernel/pull/2715
