### ISSUE TITLE
[Backend]Stream Generation Support for the editor

### ISSUE THREAD

**Issue by sajithshn** [wso2/streaming-integrator#68]
In ETL use cases often the data source will be file or DB. In both of these cases, we can derive the data field name and data type.

For files, we can check the headers and the data values and guess the data type and the filed name.

For DBs, we can check the DDL and then get the required information.

In the editor, one should be able to point to a file or a DB and automatically generate the stream definition.

**Comment by sajithshn** [comment]
@dnwick : Can you please mention the PRs here?

**Comment by dnwick** [comment]
Backend and some of the frontend of this feature was done by following,
https://github.com/wso2/carbon-analytics/pull/1795
https://github.com/wso2/carbon-analytics/pull/1796
https://github.com/wso2/carbon-analytics/pull/1799
https://github.com/wso2/carbon-analytics/pull/1821
https://github.com/wso2/carbon-analytics/pull/1824
https://github.com/wso2/carbon-analytics/pull/1828
https://github.com/wso2/carbon-analytics/pull/1829
https://github.com/wso2/carbon-analytics/pull/1833
