### ISSUE TITLE
[UI] Stream Generation

### ISSUE THREAD

**Issue by sajithshn** [wso2/streaming-integrator#69]
Develop a UI for users to generate streams by pointing to files and DB tables.

-Users should be able to browse and select a file. 
-For DBs users should be able to provide the connection details and point to a table
- Once the table or the file is selected, generate stream with filed names and data types

**Comment by sajithshn** [comment]
@AnuGayan : can you please mention the PR of this issue and close the issue.

**Comment by AnuGayan** [comment]
This was implemented through 
https://github.com/wso2/carbon-analytics/pull/1811 
https://github.com/wso2/carbon-analytics/pull/1818
https://github.com/wso2/carbon-analytics/pull/1820
https://github.com/wso2/carbon-analytics/pull/1830
