### ISSUE TITLE
Frequent changes between Siddhi App start and stop produces NullPointerException when using file

### ISSUE THREAD

**Issue by ramindu90** [wso2/streaming-integrator#98]
**Description:**
When using any file extension in the tooling and if we start and stop the siddhi application several times really fast, then it give a NullPointerException.
<img width="961" alt="Screen Shot 2020-03-26 at 11 39 17 AM" src="https://user-images.githubusercontent.com/10056966/77615897-76400880-6f56-11ea-8f6a-e9e2886d33c8.png">

**Steps to reproduce:**
Deploy CSVDefaultMapping sample in the tooling.
Click on start and play button at a fast rate.

**Related Issues:**
https://github.com/siddhi-io/siddhi-io-file/issues/89

**Comment by dnwick** [comment]
@ramindu90 was this a issue from backend code ? Did we fix anything

**Comment by ramindu90** [comment]
@dnwick this is fixed with https://github.com/siddhi-io/siddhi-io-file/commit/9b46545dc295775c87bd6e9db02f48f8b71a72a4
